import './globals.css'
import {Roboto_Flex as Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets:['latin'],
  variable:'--font-roboto',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} bg-gray-900 font-sans text-gray-100`}>
        <header className=''>Header</header>
        {children}
      </body>
    </html>
  )
}
